name: Build

on:
  push:
    branches:
    - master
    - ci-*
  pull_request:
    branches:
    - master

env:
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: Setup LLVM and MLIR
      run: |
        conda install -c conda-forge libmlir20 libllvm20
        ls $CONDA
        ls $CONDA/lib/cmake/llvm
        ls $CONDA/lib/cmake/mlir

    - name: Configure CMake
      run: |
        cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}\
          -DMLIR_DIR=$CONDA/lib/cmake/mlir -DLLVM_DIR=$CONDA/lib/cmake/llvm

    - name: Build
      run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}
